site_name: International Gangsters Wiki
markdown_extensions:
  - tables
plugins:
  - table-reader
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
extra_css:
  - stylesheets/extra.css
theme:
  features:
    - navigation.sections
  name: material
  logo: https://cdn.internationalgangsters.com/icons/favicon.ico
  favicon: https://cdn.internationalgangsters.com/icons/favicon.ico
  palette:
    scheme: slate
    primary: blue
    accent: deep orange
nav:
  - Visit Game: 'https://internationalgangsters.com'
  - Home: '../'
  - FAQ: 'faq'
  - Season 4: 'season_4'
  - Season 5: 'season_5'
  - New Starter Guide: 'new_starter_guide'
  - Making Money: 'making_money'
  - Game Rules: 'game_rules'
  - Update Log: 'update_log'
  - Information:
    - Seasons: information/seasons
    - Daily Rewards: information/daily_rewards
    - Statistics: information/statistics
    - Game Records: information/game_records
    - Game Objectives: information/game_objectives
    - Profile: information/profile
    - Notepad: information/notepad
    - Properties: information/properties
    - My Properties: information/my_properties
    - Helpdesk: information/helpdesk
    - Users Online: information/users_online
    - Promotional Codes: information/promotional_codes
    - Raffles: information/raffle
    - Latest News: information/latest_news
  - Ranking:
    - Crimes: ranking/crimes
    - Jail: ranking/jail
    - GTA: ranking/gta
    - Repair: ranking/repair
    - Missions: ranking/missions
    - Heist: ranking/heist
  - Messaging:
    - Send Message: messaging/send_message
    - Mailbox: messaging/mailbox
    - Crew Forum: messaging/crew_forum
    - Main Forum: messaging/main_forum
    - Design Forum: messaging/design_forum
    - Entertainment Forum: messaging/entertainment_forum
  - Money:
    - Bank: money/bank
    - Points: money/points
    - Quicktrade: money/quicktrade
    - Drug Trade: money/drug_trade
    - Stock Market: money/stock_market
    - Betting Shop: money/betting_shop
    - My Inventory: money/my_inventory
    - Crates: money/crates
    - Buy Cars: money/buy_cars
    - Sell Cars: money/sell_cars
    - Formula 1: money/f1
    - Dice Game: money/dice_game
    - Roulette: money/roulette
    - Race Track: money/race_track
    - Blackjack: money/blackjack
    - Multidice Game: money/multidice_game
    - Video Poker: money/video_poker
    - Crack The Safe: money/crack_the_safe
  - Offence:
    - Armoury: offence/armoury
    - Gun Locker: offence/gun_locker
    - Scrapyard: offence/scrapyard
    - Hitlist: offence/hitlist
    - Kill: offence/kill
    - Battle Arena: offence/battle_arena
    - Dead > Alive: offence/dead_alive
    - Airport: offence/airport
    - Travel by Car: offence/travel_by_car
    - Attempts: offence/attempts
    - Witness Statements: offence/witness_statements
  - Crews:
    - Crews: crews/crews
    - Member HQ: crews/member_hq
    - Crew Rackets: crews/crew_rackets
    - Crew Applications: crews/crew_applications
    - Crew OC: crews/crew_oc
    - Crew Message Members: crews/crew_message_members
    - Member Management: crews/member_management
    - Crew Management: crews/crew_management
    - Crew War: crews/crew_war
